-- Use CASCADE to drop tables even if other tables have foreign keys pointing to them
-- DROP TABLE IF EXISTS LOYALTY_LEVEL CASCADE;
-- DROP TABLE IF EXISTS CONTACT_PREFERENCE CASCADE;
-- DROP TABLE IF EXISTS ROLE CASCADE;
-- DROP TABLE IF EXISTS POWER_BACKUP CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
-- DROP TABLE IF EXISTS VEHICLE CASCADE;
-- DROP TABLE IF EXISTS PARKING_SESSION CASCADE;
-- DROP TABLE IF EXISTS CAMERA_DEVICE CASCADE;
-- DROP TABLE IF EXISTS PAYMENT CASCADE;
-- DROP TABLE IF EXISTS PAYMENT_LINK CASCADE;
-- DROP TABLE IF EXISTS RECEIPT CASCADE;
-- DROP TABLE IF EXISTS OVERSTAY_LOG CASCADE;
-- DROP TABLE IF EXISTS CHARGE CASCADE;
-- DROP TABLE IF EXISTS NOTIFICATION_LOG CASCADE;
-- DROP TABLE IF EXISTS VEHICLE_ENTRY CASCADE;
-- DROP TABLE IF EXISTS AI_RECOGNITION CASCADE;
-- DROP TABLE IF EXISTS CONFIDENCE_SCORE CASCADE;
-- DROP TABLE IF EXISTS FACIAL_RECOGNITION_EVENT CASCADE;
-- DROP TABLE IF EXISTS TICKET CASCADE;
-- DROP TABLE IF EXISTS LICENSE_PLATE_RECOGNITION CASCADE;
-- DROP TABLE IF EXISTS DATA_RECORD CASCADE;
-- DROP TABLE IF EXISTS "USER" CASCADE;
-- DROP TABLE IF EXISTS SYSTEM_ACTION CASCADE;
-- DROP TABLE IF EXISTS AUDIT_LOG CASCADE;
-- DROP TABLE IF EXISTS SYSTEM CASCADE;

CREATE TABLE IF NOT EXISTS LOYALTY_LEVEL (
    LoyaltyLevelID SERIAL PRIMARY KEY,
    LevelName      VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTACT_PREFERENCE (
    ContactPreferenceID SERIAL PRIMARY KEY,
    PreferenceType      VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLE (
    RoleID   SERIAL PRIMARY KEY,
    RoleName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS POWER_BACKUP (
    PowerBackupID SERIAL PRIMARY KEY,
    Status        VARCHAR(50)
);

-- Core entity tables

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CustomerID            SERIAL PRIMARY KEY,
    FirstName             VARCHAR(255) NOT NULL,
    LastName              VARCHAR(255) NOT NULL,
    Email                 VARCHAR(255),
    MobileNumber          VARCHAR(20) UNIQUE NOT NULL,
    CarRegistration       VARCHAR(20) UNIQUE,
    ProfilePhoto          TEXT,
    Role                  VARCHAR(20) DEFAULT 'customer',
    FreeParkingDuration   INT DEFAULT 30,
    DailyChargeLimit      DECIMAL(10, 2) DEFAULT 100.00,
    LoyaltyLevelID        INT,
    ContactPreferenceID   INT UNIQUE,
    PasswordHash          VARCHAR(255) NOT NULL,
    ResetToken            VARCHAR(255),
    ResetTokenExpiry      TIMESTAMP,
    ResetOTP              VARCHAR(6),
    ResetOTPExpiry        TIMESTAMP,
    FOREIGN KEY (LoyaltyLevelID) REFERENCES LOYALTY_LEVEL(LoyaltyLevelID),
    FOREIGN KEY (ContactPreferenceID) REFERENCES CONTACT_PREFERENCE(ContactPreferenceID)
);

CREATE TABLE IF NOT EXISTS VEHICLE (
    VehicleID  SERIAL PRIMARY KEY,
    CustomerID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE CAMERA_DEVICE (
    CameraDeviceID SERIAL PRIMARY KEY,
    Location       VARCHAR(255)
);

CREATE TABLE PARKING_SESSION (
    SessionID          SERIAL PRIMARY KEY,
    CustomerID         INT NOT NULL,
    VehicleID          INT NOT NULL,
    GateCameraDeviceID INT NOT NULL,
    SessionTimeout     TIMESTAMP,
    ExitAuthorization  BOOLEAN,
    EntryTime          TIMESTAMP,
    ExitTime           TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    FOREIGN KEY (VehicleID) REFERENCES VEHICLE(VehicleID),
    FOREIGN KEY (GateCameraDeviceID) REFERENCES CAMERA_DEVICE(CameraDeviceID)
);

CREATE TABLE PAYMENT (
    PaymentID  SERIAL PRIMARY KEY,
    SessionID  INT NOT NULL,
    Amount     DECIMAL(10, 2),
    PaymentMethod VARCHAR(50) DEFAULT 'card',
    Status     VARCHAR(20) DEFAULT 'completed',
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID)
);

CREATE TABLE PAYMENT_LINK (
    PaymentLinkID SERIAL PRIMARY KEY,
    PaymentID     INT UNIQUE NOT NULL,
    Url           VARCHAR(500),
    ExpiresAt     TIMESTAMP,
    FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID)
);

CREATE TABLE RECEIPT (
    ReceiptID SERIAL PRIMARY KEY,
    PaymentID INT UNIQUE NOT NULL,
    FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID)
);

CREATE TABLE OVERSTAY_LOG (
    OverstayLogID   SERIAL PRIMARY KEY,
    SessionID       INT UNIQUE NOT NULL,
    OverstayMinutes INT,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID)
);

CREATE TABLE CHARGE (
    ChargeID      SERIAL PRIMARY KEY,
    OverstayLogID INT UNIQUE NOT NULL,
    Amount        DECIMAL(10, 2),
    FOREIGN KEY (OverstayLogID) REFERENCES OVERSTAY_LOG(OverstayLogID)
);

CREATE TABLE NOTIFICATION_LOG (
    NotificationLogID SERIAL PRIMARY KEY,
    SessionID         INT NOT NULL,
    CustomerID        INT NOT NULL,
    Channel           VARCHAR(50),
    SentAt            TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID),
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE VEHICLE_ENTRY (
    VehicleEntryID SERIAL PRIMARY KEY,
    SessionID      INT UNIQUE NOT NULL,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID)
);

CREATE TABLE AI_RECOGNITION (
    AiRecognitionID SERIAL PRIMARY KEY,
    VehicleEntryID  INT UNIQUE NOT NULL,
    FOREIGN KEY (VehicleEntryID) REFERENCES VEHICLE_ENTRY(VehicleEntryID)
);

CREATE TABLE CONFIDENCE_SCORE (
    ConfidenceScoreID SERIAL PRIMARY KEY,
    AiRecognitionID   INT UNIQUE NOT NULL,
    Score             FLOAT,
    FOREIGN KEY (AiRecognitionID) REFERENCES AI_RECOGNITION(AiRecognitionID)
);

CREATE TABLE FACIAL_RECOGNITION_EVENT (
    EventID           SERIAL PRIMARY KEY,
    SessionID         INT NOT NULL,
    CameraDeviceID    INT NOT NULL,
    ConfidenceScoreID INT NOT NULL,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID),
    FOREIGN KEY (CameraDeviceID) REFERENCES CAMERA_DEVICE(CameraDeviceID),
    FOREIGN KEY (ConfidenceScoreID) REFERENCES CONFIDENCE_SCORE(ConfidenceScoreID)
);

CREATE TABLE TICKET (
    TicketID       SERIAL PRIMARY KEY,
    VehicleEntryID INT UNIQUE NOT NULL,
    FOREIGN KEY (VehicleEntryID) REFERENCES VEHICLE_ENTRY(VehicleEntryID)
);

CREATE TABLE LICENSE_PLATE_RECOGNITION (
    LprID          SERIAL PRIMARY KEY,
    VehicleEntryID INT UNIQUE NOT NULL,
    FOREIGN KEY (VehicleEntryID) REFERENCES VEHICLE_ENTRY(VehicleEntryID)
);

CREATE TABLE DATA_RECORD (
    DataRecordID SERIAL PRIMARY KEY,
    SessionID    INT NOT NULL,
    FOREIGN KEY (SessionID) REFERENCES PARKING_SESSION(SessionID)
);

-- User / system management tables

CREATE TABLE "USER" (
    UserID SERIAL PRIMARY KEY,
    RoleID INT NOT NULL,
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

CREATE TABLE SYSTEM_ACTION (
    SystemActionID SERIAL PRIMARY KEY,
    UserID         INT NOT NULL,
    ActionType     VARCHAR(100),
    ActionAt       TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES "USER"(UserID)
);

CREATE TABLE AUDIT_LOG (
    AuditLogID     SERIAL PRIMARY KEY,
    SystemActionID INT UNIQUE NOT NULL,
    Details        VARCHAR(1000),
    FOREIGN KEY (SystemActionID) REFERENCES SYSTEM_ACTION(SystemActionID)
);

CREATE TABLE SYSTEM (
    SystemID      SERIAL PRIMARY KEY,
    PowerBackupID INT UNIQUE NOT NULL,
    FOREIGN KEY (PowerBackupID) REFERENCES POWER_BACKUP(PowerBackupID)
);

-- DATABASE MAINTENANCE
-- Run these to ensure existing tables match the current code requirements

-- Add CarRegistration if it was missing from an older version of the table
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS CarRegistration VARCHAR(20) UNIQUE;

-- Add Password Reset columns if they are missing
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS ResetToken VARCHAR(255);
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS ResetTokenExpiry TIMESTAMP;
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS ResetOTP VARCHAR(6);
ALTER TABLE CUSTOMER ADD COLUMN IF NOT EXISTS ResetOTPExpiry TIMESTAMP;

-- Allow multiple accounts to share the same email address if necessary
ALTER TABLE CUSTOMER DROP CONSTRAINT IF EXISTS customer_email_key;
